### ISSUE TITLE
Quiestion: how to efficiently and fast transfer a docker image from the host to the Jetson?

### ISSUE THREAD

**Issue by ikhann** [NVIDIA-ISAAC-ROS/isaac_ros_common#53]
Hi!

I am faced with the issue of a need for free disk space when transferring the Docker image to Jetson. 
I got the error "no space left on device" when running the command "docker load <image>":

![image](https://user-images.githubusercontent.com/21182465/214859007-176eb063-bb4d-4195-964d-4f48d0f8a0ce.png)

But at the same time, I see that Jetson has more space than required for the docker image.

I will be very pleased if you help solve it and advise how to efficiently and fast transfer a docker image with a high degree of compression and load it afterward.

I really appreciate any help you can provide.

**Comment by hemalshahNV** [comment]
It might be because you end up with two copies of the Docker image on the target device: 1. The tarball you're streaming into, 2. The docker cache in /var/docker itself. Uncompressed, this could exceed the 45GBs you have available (likely ~48GB). It might be more effective to have docker running on NX populate its cache directly from the remote registry or setting up your own Docker registry locally to mirror the image to the NX perhaps. Finally, you could attach an external drive via USB to handle hosting the tarball layers from docker save and then running docker load from there.
